name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Cache outputRoot
      uses: actions/cache@v1
      with:
        path: ~/.cache/bazel
        key: bazel

    - name: Install go
      uses: actions/setup-go@v1
      with:
        go-version: '1.9.3'

    - name: Install bazelisk
      run: |
        go get github.com/bazelbuild/bazelisk
        echo "::set-env name=GOPATH::$(go env GOPATH)"
        echo "::add-path::$(go env GOPATH)/bin"

    - name: Test
      run: |
        bazelisk test //...

    - name: Build
      run: |
        bazelisk build //...
